version: 2.1

orbs:
  cli: circleci/circleci-cli@0.1.9

jobs:
  execution:
    machine: true
    steps:
    - cli/install
    - checkout
    - run:
        name: "ランタイムテスト"
        command: |
          circleci local execute --config .circleci/test.yml --job hello-world/echo-job | tee local_build_output.txt /dev/stderr | tail -n 1 | grep "Success"

workflows:
  main:
    jobs:
      - execution