version: 2.1

orbs:
  cli: circleci/circleci-cli@0.1.9

jobs:
  expansion:
    executor: cli/default
    steps:
    - cli/install
    - checkout
    - run:
        name: "Install yq"
        command: |
          sudo apt update && \
          sudo apt-get install jq python-pip python-dev && \
          sudo pip install yq
    - run:
        name: "展開テスト"
        command: |
          result=$(circleci config process .circleci/test.yml | yq '.jobs."hello-world/echo-job".steps[0].run.command')
          echo ${result} | grep "Hello, CircleCI"

workflows:
  main:
    jobs:
      - expansion