version: 2.1

orbs:
  cli: circleci/circle-cli@0.1.5

jobs:
  validation:
    executor: cli/default
    steps:
    - cli/install
    - checkout
    - run:
        name: "バリデーション"
        command: circlci orb validate ./src/hello-orb.yml

workflows:
  main:
    jobs:
      - validation