orbs:
  orb-tools: circleci/orb-tools@10.0.3

version: 2.1

workflows:
  publish-dev-orb:
    jobs:
      - orb-tools/publish-dev:
          orb-path: ./src/hello-orb.yml
          orb-name: yuta-orbs/second-hello
          validate: true
          checkout: true