version: 2.1
description: "My first orb"

executors:
  default:
    docker:
      - image: busybox

jobs:
   echo-job:
     description: "echo job!"
     parameters:
       to:
         type: string
         default: "World"
     executor: default
     steps:
       - echo-command:
           to: << parameters.to >>

commands:
  echo-command:
    description: "echo コマンド"
    parameters:
      to:
        type: string
        default: "World"
    steps:
      - run: echo "Hello, << parameters.to >>"